Repository WSU-CEG-6110-4410/UncleBuck-sCraft, pull requests merged in 2022-04, with the labels that each got.

#13 Change comments to Doxygen friendly format
  src/world.c
Labels: documentation

#14 Revert "Change comments to Doxygen friendly format"
  src/world.c
Labels: documentation

#15 Add Doxygen style comments
  src/world.c
Labels: documentation

#17 Update world.c
  src/world.c
Labels: documentation

#21 Create Doxyfile template
  src/Doxyfile
Labels: documentation

#25 Change Project Name and Description
  src/Doxyfile
Labels: documentation

#30 clouds have been removed
  src/config.h
Labels: user story

#32 the clouds have been removed again
  src/config.h
Labels: user story

#36 left hand controls now active
  src/config.h
  src/main.c
Labels: user story

#38 Logic for increasing travel speed added
  src/main.c
Labels: enhancement

#40 Updated README.md to reflect issue #37
  BUCK_README.md
Labels: enhancement

#41 Revert "Logic for increasing travel speed added"
  src/main.c
Labels: bug

#45 Adding Diamonds to Items
  src/item.h
Labels: documentation, user story

#46 44 more addition to item 34 topaz needs to be added
  src/item.c
  src/item.h
Labels: documentation, user story

#47 Adding Gold
  src/item.h
Labels: documentation, user story

#49 Adding Gold to the Buildable items.
  src/item.c
Labels: documentation, enhancement, user story
